preload = /home/skyline/Pictures/Wallpapers/a_foggy_landscape_with_trees_and_grass.jpg

splash = false

wallpaper {
    monitor = DP-1
    path = /home/skyline/Pictures/Wallpapers/a_foggy_landscape_with_trees_and_grass.jpg
    fit_mode = cover
}

wallpaper {
    monitor = HDMI-A-1
    path = /home/skyline/Pictures/Wallpapers/a_foggy_landscape_with_trees_and_grass.jpg
    fit_mode = cover
}
