$terminal = alacritty
$fileManager = dolphin
$browser = chromium --disable-features=WaylandWpColorManagerV1
$menu = rofi -show drun
$screenshot = hyprshot -m region --clipboard-only
$logout = hyprlock
$discord = discord

