exec-once = sh -lc 'command -v gnome-keyring-daemon >/dev/null && exec gnome-keyring-daemon --start --components=secrets,ssh'
exec-once = sh -lc 'command -v quickshell >/dev/null && exec quickshell -d'
exec-once = sh -lc 'command -v systemctl >/dev/null && systemctl --user start hyprpolkitagent'
exec-once = sh -lc 'command -v hypridle >/dev/null && exec hypridle'
exec-once = [workspace 1 silent] $terminal
exec-once = sh -lc 'command -v easyeffects >/dev/null && exec easyeffects --hide-window'
